# main text of home
name: Andrea Mattavelli
bio: Software engineer, Monday hater, food lover.

external-image: false
picture: assets/images/bio-photo.png

resume: false

url: https://andreamattavelli.github.io

permalink: /:title/

github: andreamattavelli
twitter: amattavelli
linkedin: andreamattavelli
#email: andreamattavelli@gmail.com

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

animation: true

plugins:
  - jemoji

scholar:
  style: _bibliography/citations.csl
  locale: en
  sort_by: none
  order: reverse
  source: _bibliography
  bibliography: publication
  bibliography_template: bibtemplate
  replace_strings: true
  details_dir:    bibliography
  details_link:   Details
  query: "@*"
